name: laska
description: A simple command-line application.
# version: 1.0.0
homepage: https://tenderowl.com/work/laska

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  mime: ^0.9.7
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
