name: laska
description: A simple command-line application.
# version: 1.0.0
homepage: https://tenderowl.com/work/laska

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  mime: ^1.0.5
  mime_type: ^1.0.0
  event: ^2.1.2
#  path: ^1.7.0

dev_dependencies:
  lints: ^4.0.0
